apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: user-java
        image: registrywnu3987.azurecr.io/tripinsights/user-java:v1
        env:
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secretpassword
              key: SQL_PASSWORD
        - name: SQL_USER
          value: "sqladminwNu3987"
        - name: SQL_SERVER
          value: "sqlserverwnu3987.database.windows.net"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/user-java/healthcheck
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/user-java/healthcheck
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
        ports:
        - containerPort: 80
          name: user-java
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
spec:
  ports:
  - port: 80
  selector:
    app: user-java